apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alerts
  namespace: prometheus-monitoring
spec:
  groups:
    - name: pod-restart-alerts
      rules:
        - alert: PodRestartCountHigh
          expr: sum(kube_pod_container_status_restarts_total) by (pod, namespace) > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} has a high restart count"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value }} times in the last minute. This could indicate a problem with the application or infrastructure."