apiVersion: v1
data:
  alertmanager.yaml: |+
    global:
      resolve_timeout: 5m

    receivers:
      - name: 'email-receiver'
        sns_configs:
          - api_url: https://sns.us-east-1.amazonaws.com
            topic_arn: arn:aws:sns:us-east-1:038462756869:Group3PrometheusAlert
            sigv4:
              region: us-east-1
              access_key: <AWS_ACCESS_KEY>
              secret_key: <AWS_SECRET_KEY>

    route:
      receiver: 'email-receiver'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h